/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ca.thefriendlycoder.spockpertestlogger

/**
 * Entrypoint class for our plugin
 */
class SpockPerTestLoggerPlugin {
    void fn() {

    }
}
