/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ca.thefriendlycoder.spockpertestlogger

import spock.lang.Specification
import spock.lang.Subject
import spock.lang.TempDir
import spock.util.EmbeddedSpecRunner

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths

@Subject(SpockPerTestLoggerExtension)
class SpockPerTestLoggerExtensionTest extends Specification {
    @TempDir
    Path tempdir

    def "Test log folder gets created"() {
        given: "A temp folder that doesn't already exist"
        def expPath = tempdir.resolve("fubar")

        and: "A sample Spock test spec"
        def specRunner = new EmbeddedSpecRunner()
        specRunner.throwFailure = false
        specRunner.configurationScript {
            PerTestLogger {
                logPath expPath.toString()
            }
        }

        when: "We try running the sample spec"
        def results = specRunner.runClass(SampleTest)

        then: "The test suite should succeed without error"
        results.testEvents()
            .debug()
            .assertStatistics(stats -> stats.failed(0))

        and: "The log folder should have been created by the plugin"
        expPath.toFile().exists()
    }

    def "Test log folder already exists"() {
        given: "A temp folder that already exists"
        def expPath = tempdir.resolve("fubar")
        Files.createDirectories(expPath)

        and: "A sample Spock test spec"
        def specRunner = new EmbeddedSpecRunner()
        specRunner.throwFailure = false
        specRunner.configurationScript {
            PerTestLogger {
                logPath expPath.toString()
            }
        }

        when: "We try running the sample spec"
        def results = specRunner.runClass(SampleTest)

        then: "The test suite should succeed without error"
        results.testEvents()
            .debug()
            .assertStatistics(stats -> stats.failed(0))
    }

    def "Test log file gets created"() {
        given: "A sample Spock test spec"
        def specRunner = new EmbeddedSpecRunner()
        specRunner.throwFailure = false
        specRunner.configurationScript {
            PerTestLogger {
                logPath tempdir.toString()
            }
        }
        // Expected output data
        def expPath = tempdir.resolve(Paths.get("SampleTest", "test method.log"))

        when: "We try running the sample spec"
        def results = specRunner.runClass(SampleTest)

        then: "The test suite should succeed without error"
        results.testEvents()
            .debug()
            .assertStatistics(stats -> stats.failed(0))

        and: "The log file should have been created by the plugin"
        expPath.toFile().exists()
    }

    def "Test log folder gets recreated"() {
        given: "A temp folder that contains dirty data"
        def testFile = tempdir.resolve("fubar.log").toFile()
        testFile.createNewFile()

        and: "A sample Spock test spec"
        def specRunner = new EmbeddedSpecRunner()
        specRunner.throwFailure = false
        specRunner.configurationScript {
            PerTestLogger {
                logPath tempdir.toString()
            }
        }
        // Expected output data
        def expPath = tempdir.resolve(Paths.get("SampleTest", "test method.log"))

        when: "We try running the sample spec"
        def results = specRunner.runClass(SampleTest)

        then: "The test suite should succeed without error"
        results.testEvents()
            .debug()
            .assertStatistics(stats -> stats.failed(0))

        and: "The dirty log data should no longer exist"
        !testFile.exists()

        and: "New test output should be created in its place"
        expPath.toFile().exists()
    }

    def "Test log file gets populated"() {
        given: "A sample Spock test spec"
        def specRunner = new EmbeddedSpecRunner()
        specRunner.throwFailure = false
        specRunner.configurationScript {
            PerTestLogger {
                logPath tempdir.toString()
            }
        }
        // Expected output data
        def expPath = tempdir.resolve(Paths.get("SampleTest", "test method.log"))

        when: "We try running the sample spec"
        def results = specRunner.runClass(SampleTest)

        then: "The test suite should succeed without error"
        results.testEvents()
            .debug()
            .assertStatistics(stats -> stats.failed(0))

        and: "The log file should have been created by the plugin"
        expPath.toFile().exists()

        and: "The log file contains the correct output"
        expPath.toFile().text == "Inside fake unit test\n"
    }
}
