/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ca.thefriendlycoder.spockpertestlogger

//import org.gradle.testfixtures.ProjectBuilder
import org.slf4j.LoggerFactory
import spock.lang.Specification

/**
 * A simple unit test for the 'spockpertestlogger.greeting' plugin.
 */
class SpockPerTestLoggerPluginTest extends Specification {
//    def "plugin registers task"() {
//        given:
//        def project = ProjectBuilder.builder().build()
//
//        when:
//        project.plugins.apply("ca.thefriendlycoder.spockpertestlogger")
//
//        then:
//        project.tasks.named("ptlShowErrors") != null
//    }

    def "tryme"() {
        expect:
        //def temp = SpockPerTestLoggerExtension;
        LoggerFactory.getLogger(SpockPerTestLoggerPluginTest.class).error("KSP was here in unit test")
        LoggerFactory.getLogger(SpockPerTestLoggerPluginTest.class).info("KSP2 was here in unit test")
    }
}
