/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ca.thefriendlycoder.spockpertestlogger

import spock.lang.Specification

/**
 * A simple unit test for the 'spockpertestlogger.greeting' plugin.
 */
class SpockPerTestLoggerPluginTest extends Specification {
    def "sample"() {
        expect:
        true
    }
}
